CREATE TABLE IF NOT EXISTS restaurants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category ENUM('italian', 'asian', 'russian', 'seafood', 'french', 'georgian', 'mexican', 'american') NOT NULL,
    cuisine_type VARCHAR(100),
    address VARCHAR(255),
    description TEXT,
    image_url VARCHAR(255),
    website VARCHAR(255),
    contact_phone VARCHAR(50),
    hours VARCHAR(100),
    price_range VARCHAR(10),
    min_price DECIMAL(10,2),
    delivery_time VARCHAR(20),
    rating DECIMAL(3,2) DEFAULT 0,
    criteria JSON,
    slug VARCHAR(255) UNIQUE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reviews (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    restaurant_id INT,
    restaurant_name VARCHAR(255) NOT NULL,
    rating INT NOT NULL,
    comment TEXT NOT NULL,
    food_rating INT DEFAULT 0,
    service_rating INT DEFAULT 0,
    atmosphere_rating INT DEFAULT 0,
    price_rating INT DEFAULT 0,
    cleanliness_rating INT DEFAULT 0,
    likes INT DEFAULT 0,
    has_receipt BOOLEAN DEFAULT FALSE,
    receipt_photo VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (restaurant_id) REFERENCES restaurants(id)
); 